// ============================================================
// RAMYA-COOK image resolver — run on a machine WITH internet:
//   node scripts/resolve-images.mjs           (hotlink verified URLs)
//   node scripts/resolve-images.mjs --download (also self-host to public/dishes)
//
// It resolves a REAL, verified photo for each recipe/product via a cascade
// (TheMealDB → Wikimedia Commons), records attribution, and writes
// src/data/images.generated.ts (which the app merges over the keyword fallback).
// Nothing here runs in the browser; no API keys required.
// ============================================================
import { writeFileSync, mkdirSync, createWriteStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';

const DOWNLOAD = process.argv.includes('--download');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Load recipe/product names without a TS toolchain: read the built data via a
// tiny regex over the source files (ids + names).
import { readFileSync, readdirSync } from 'node:fs';
function recipesFromSource() {
  const out = [];
  for (const f of readdirSync('src/data').filter((x) => x.startsWith('recipes-'))) {
    const t = readFileSync(`src/data/${f}`, 'utf8');
    const re = /id:\s*'([a-z0-9-]+)'[\s\S]{0,120}?name:\s*'([^']+)'/g;
    let m;
    while ((m = re.exec(t))) out.push({ id: m[1], name: m[2].replace(/\\'/g, "'") });
  }
  return out;
}

async function verify(url) {
  try {
    const r = await fetch(url, { method: 'HEAD', redirect: 'follow' });
    return r.ok && (r.headers.get('content-type') || '').startsWith('image/');
  } catch { return false; }
}

async function fromMealDB(name) {
  try {
    const r = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${encodeURIComponent(name)}`);
    const j = await r.json();
    const url = j.meals?.[0]?.strMealThumb;
    return url ? { src: url, credit: 'Photo: TheMealDB' } : null;
  } catch { return null; }
}

async function fromCommons(name) {
  try {
    const api = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrsearch=${encodeURIComponent(name + ' food')}&gsrlimit=1&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=800&format=json&origin=*`;
    const r = await fetch(api);
    const j = await r.json();
    const pages = j.query?.pages ? Object.values(j.query.pages) : [];
    const info = pages[0]?.imageinfo?.[0];
    if (!info?.thumburl) return null;
    const artist = info.extmetadata?.Artist?.value?.replace(/<[^>]+>/g, '') || 'Wikimedia Commons';
    const lic = info.extmetadata?.LicenseShortName?.value || 'CC';
    return { src: info.thumburl, credit: `Photo: ${artist} / ${lic} (Wikimedia Commons)` };
  } catch { return null; }
}

async function download(id, url) {
  mkdirSync('public/dishes', { recursive: true });
  const ext = (url.split('?')[0].match(/\.(jpg|jpeg|png|webp)$/i)?.[1] || 'jpg').toLowerCase();
  const path = `public/dishes/${id}.${ext}`;
  const res = await fetch(url);
  if (!res.ok || !res.body) throw new Error(`download failed ${url}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(path));
  return `/dishes/${id}.${ext}`;
}

const recipes = recipesFromSource();
const out = {};
let ok = 0;
for (const { id, name } of recipes) {
  const hit = (await fromMealDB(name)) || (await fromCommons(name));
  if (hit && (await verify(hit.src))) {
    if (DOWNLOAD) {
      try { hit.src = await download(id, hit.src); } catch { /* keep hotlink */ }
    }
    out[id] = { src: hit.src, credit: hit.credit };
    ok++;
    console.log(`✓ ${id}`);
  } else {
    console.log(`· ${id} (keyword fallback)`);
  }
  await sleep(200); // be polite to the APIs
}

const body = `// AUTO-GENERATED by scripts/resolve-images.mjs — do not edit by hand.
import type { DishPhoto } from './images';

export const GENERATED_IMAGES: Record<string, DishPhoto> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync('src/data/images.generated.ts', body);
console.log(`\nResolved ${ok}/${recipes.length} verified photos → src/data/images.generated.ts`);
console.log('The rest use the deterministic keyword photo (still real). Commit the generated file' + (DOWNLOAD ? ' and public/dishes/.' : '.'));
