// AUTO-GENERATED by scripts/resolve-images.mjs — do not edit by hand.
// Ships empty; run `npm run resolve-images` on a machine with internet to fill
// it with verified, self-hosted dish photos (which override the keyword fallback).
import type { DishPhoto } from './images';

export const GENERATED_IMAGES: Record<string, DishPhoto> = {};
