// AUTO-GENERATED by scripts/resolve-images.mjs — do not edit by hand.
import type { DishPhoto } from './images';

export const GENERATED_IMAGES: Record<string, DishPhoto> = {
  "plain-dosa": {
    "src": "/dishes/plain-dosa.jpg",
    "credit": "Photo: JITENDRA KUMAR JANGIR / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "mysore-masala-dosa": {
    "src": "/dishes/mysore-masala-dosa.jpg",
    "credit": "Photo: Kaushik AP / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "onion-dosa": {
    "src": "/dishes/onion-dosa.jpg",
    "credit": "Photo: Srishti Singh / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "ghee-dosa": {
    "src": "/dishes/ghee-dosa.jpg",
    "credit": "Photo: Deviselvam / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rava-dosa": {
    "src": "/dishes/rava-dosa.jpg",
    "credit": "Photo: SamarthBhandavale / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "set-dosa": {
    "src": "/dishes/set-dosa.jpg",
    "credit": "Photo: Yakshitha / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "neer-dosa": {
    "src": "/dishes/neer-dosa.jpg",
    "credit": "Photo: DreamyFlutura11 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "millet-dosa": {
    "src": "/dishes/millet-dosa.jpg",
    "credit": "Photo: Srravya / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "cheese-dosa": {
    "src": "/dishes/cheese-dosa.jpg",
    "credit": "Photo: Kaushik AP / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "podi-dosa": {
    "src": "/dishes/podi-dosa.jpg",
    "credit": "Photo: Dharshana Nathan / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "pesarattu": {
    "src": "/dishes/pesarattu.jpg",
    "credit": "Photo: MVishnuV / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "uthappam": {
    "src": "/dishes/uthappam.jpg",
    "credit": "Photo: cool_spark from Bengaluru, India / CC BY 2.0 (Wikimedia Commons)"
  },
  "adai": {
    "src": "/dishes/adai.jpg",
    "credit": "Photo: Vidya pmysore / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "appam": {
    "src": "/dishes/appam.jpg",
    "credit": "Photo: Avinashvh1n1 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "idiyappam": {
    "src": "/dishes/idiyappam.jpg",
    "credit": "Photo: Krishmarch17 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "puttu": {
    "src": "/dishes/puttu.jpg",
    "credit": "Photo: Belrien12 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rava-idli": {
    "src": "/dishes/rava-idli.jpg",
    "credit": "Photo: Amanrvet / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "mini-idli": {
    "src": "/dishes/mini-idli.jpg",
    "credit": "Photo: Advaitj11 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "paniyaram": {
    "src": "/dishes/paniyaram.jpg",
    "credit": "Photo: Sengolkural / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "akki-roti": {
    "src": "/dishes/akki-roti.jpg",
    "credit": "Photo: Draupadigamy9305 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "raita": {
    "src": "/dishes/raita.jpg",
    "credit": "Photo: Sonali Nath / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "veg-fried-rice": {
    "src": "/dishes/veg-fried-rice.jpg",
    "credit": "Photo: Biswarup Ganguly / CC BY 3.0 (Wikimedia Commons)"
  },
  "gulab-jamun": {
    "src": "/dishes/gulab-jamun.jpg",
    "credit": "Photo: Aparna Balasubramanian / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "masala-dosa": {
    "src": "/dishes/masala-dosa.jpg",
    "credit": "Photo: Marajozkee / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "idli": {
    "src": "/dishes/idli.jpg",
    "credit": "Photo: Mdsmds0 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "ven-pongal": {
    "src": "/dishes/ven-pongal.jpg",
    "credit": "Photo: Raksanand / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "medu-vada": {
    "src": "/dishes/medu-vada.jpg",
    "credit": "Photo: Andy Li / CC0 (Wikimedia Commons)"
  },
  "coconut-chutney": {
    "src": "/dishes/coconut-chutney.jpg",
    "credit": "Photo: JITENDRA KUMAR JANGIR / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "chicken-chettinad": {
    "src": "/dishes/chicken-chettinad.jpg",
    "credit": "Photo: M N Swarna / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "chole": {
    "src": "/dishes/chole.jpg",
    "credit": "Photo: Renupradhul / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rajma": {
    "src": "/dishes/rajma.jpg",
    "credit": "Photo: Medhi jyoti / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "dal-makhani": {
    "src": "/dishes/dal-makhani.jpg",
    "credit": "Photo: rovingI / CC BY 2.0 (Wikimedia Commons)"
  },
  "aloo-gobi": {
    "src": "/dishes/aloo-gobi.jpg",
    "credit": "Photo: Monali.mishra / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "chole-bhature": {
    "src": "/dishes/chole-bhature.jpg",
    "credit": "Photo: Gaurav Dhwaj Khadka / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rogan-josh": {
    "src": "/dishes/rogan-josh.jpg",
    "credit": "Photo: Rajatsingh8808 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "dhokla": {
    "src": "/dishes/dhokla.jpg",
    "credit": "Photo: Purba Mukherjee / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "pav-bhaji": {
    "src": "/dishes/pav-bhaji.jpg",
    "credit": "Photo: Tanveer Ahmed / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "misal-pav": {
    "src": "/dishes/misal-pav.jpg",
    "credit": "Photo: Arundhati1312 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "vada-pav": {
    "src": "/dishes/vada-pav.jpg",
    "credit": "Photo: Rutvi Mistry / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "poha": {
    "src": "/dishes/poha.jpg",
    "credit": "Photo: Sanket Oswal / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "goan-fish-curry": {
    "src": "/dishes/goan-fish-curry.jpg",
    "credit": "Photo: goanfishcurryrice3 / CC BY-SA 2.0 (Wikimedia Commons)"
  },
  "macher-jhol": {
    "src": "/dishes/macher-jhol.jpg",
    "credit": "Photo: Sharnab neogi / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "aloo-posto": {
    "src": "/dishes/aloo-posto.jpg",
    "credit": "Photo: Hrishikes / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "litti-chokha": {
    "src": "/dishes/litti-chokha.jpg",
    "credit": "Photo: Rajeeb Dutta / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "kadala-curry": {
    "src": "/dishes/kadala-curry.jpg",
    "credit": "Photo: Devika / CC BY-SA 2.0 (Wikimedia Commons)"
  },
  "thoran": {
    "src": "/dishes/thoran.jpg",
    "credit": "Photo: Samphotography / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "bisi-bele-bath": {
    "src": "/dishes/bisi-bele-bath.jpg",
    "credit": "Photo: Munegowda K C / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "ragi-mudde": {
    "src": "/dishes/ragi-mudde.jpg",
    "credit": "Photo: Jagisnowjughead / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "kosambari": {
    "src": "/dishes/kosambari.jpg",
    "credit": "Photo: ShBees / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "mirchi-bajji": {
    "src": "/dishes/mirchi-bajji.jpg",
    "credit": "Photo: Sirwon Creations / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "hyderabadi-biryani": {
    "src": "/dishes/hyderabadi-biryani.jpg",
    "credit": "Photo: HiMyNameIsAughh / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "andhra-biryani": {
    "src": "/dishes/andhra-biryani.jpg",
    "credit": "Photo: Alnitak-Alnilam-Mintaka / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sambar-tiffin": {
    "src": "/dishes/sambar-tiffin.jpg",
    "credit": "Photo: Raksanand / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sambar-drumstick": {
    "src": "/dishes/sambar-drumstick.jpg",
    "credit": "Photo: KARANK21 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sambar-vegetable": {
    "src": "/dishes/sambar-vegetable.jpg",
    "credit": "Photo: Samphotography / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sambar-instant": {
    "src": "/dishes/sambar-instant.jpg",
    "credit": "Photo: Sangeeta Khurana / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rasam": {
    "src": "/dishes/rasam.jpg",
    "credit": "Photo: Sriram Ganesh Babu / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "tomato-rasam": {
    "src": "/dishes/tomato-rasam.jpg",
    "credit": "Photo: V.S.Pooja / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "avial": {
    "src": "/dishes/avial.jpg",
    "credit": "Photo: blackmoon / CC BY 2.0 (Wikimedia Commons)"
  },
  "lemon-rice": {
    "src": "/dishes/lemon-rice.jpg",
    "credit": "Photo: Sriraghuveer / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "parotta": {
    "src": "/dishes/parotta.jpg",
    "credit": "Photo: Romainbehar / CC0 (Wikimedia Commons)"
  },
  "upma": {
    "src": "/dishes/upma.jpg",
    "credit": "Photo: Intodustin / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "murukku": {
    "src": "/dishes/murukku.jpg",
    "credit": "Photo: Coolcheetahbangalore / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "mixture": {
    "src": "/dishes/mixture.jpg",
    "credit": "Photo: Aravind Sivaraj / CC BY-SA 3.0 (Wikimedia Commons)"
  },
  "seedai": {
    "src": "/dishes/seedai.jpg",
    "credit": "Photo: Jagisnowjughead / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sundal": {
    "src": "/dishes/sundal.jpg",
    "credit": "Photo: Lohith Aswa M / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "payasam": {
    "src": "/dishes/payasam.jpg",
    "credit": "Photo: Divya Kudua / CC BY 2.0 (Wikimedia Commons)"
  },
  "sakkarai-pongal": {
    "src": "/dishes/sakkarai-pongal.jpg",
    "credit": "Photo: selvam / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "mysore-pak": {
    "src": "/dishes/mysore-pak.jpg",
    "credit": "Photo: Jagisnowjughead / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "filter-coffee": {
    "src": "/dishes/filter-coffee.jpg",
    "credit": "Photo: Celestial Pari / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "sona-masoori": {
    "src": "/dishes/sona-masoori.jpg",
    "credit": "Photo: Leslie Seaton from Seattle, WA, USA / CC BY 2.0 (Wikimedia Commons)"
  },
  "ponni-rice": {
    "src": "/dishes/ponni-rice.jpg",
    "credit": "Photo: Thamizhpparithi Maari / CC BY-SA 3.0 (Wikimedia Commons)"
  },
  "seeraga-samba": {
    "src": "/dishes/seeraga-samba.jpg",
    "credit": "Photo: Balaji Sakthivel / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "basmati": {
    "src": "/dishes/basmati.jpg",
    "credit": "Photo: Diego Delso / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "idli-rava": {
    "src": "/dishes/idli-rava.jpg",
    "credit": "Photo: Maharana7573 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "toor-dal-pkt": {
    "src": "/dishes/toor-dal-pkt.jpeg",
    "credit": "Photo: Dahivada (Diskussion) 10:37, 1. Jun. 2016 (CEST) / Public domain (Wikimedia Commons)"
  },
  "sambar-powder-pkt": {
    "src": "/dishes/sambar-powder-pkt.jpg",
    "credit": "Photo: Keerthinellikkalaya / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "rasam-powder-pkt": {
    "src": "/dishes/rasam-powder-pkt.jpg",
    "credit": "Photo: Nithyasrm / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "paneer": {
    "src": "/dishes/paneer.jpg",
    "credit": "Photo: Sonja Pauen - Stanhopea / CC BY 2.0 de (Wikimedia Commons)"
  },
  "ghee-pkt": {
    "src": "/dishes/ghee-pkt.jpg",
    "credit": "Photo: Gaurav Dhwaj Khadka / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "coconut-oil": {
    "src": "/dishes/coconut-oil.jpg",
    "credit": "Photo: Tiia Monto / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "tamil-nadu": {
    "src": "/dishes/tamil-nadu.jpg",
    "credit": "Photo: Dhivya Bharathi Official / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "kerala": {
    "src": "/dishes/kerala.jpg",
    "credit": "Photo: Leeza George Thachil / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "karnataka": {
    "src": "/dishes/karnataka.jpg",
    "credit": "Photo: Mallikarjunasj / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "andhra-telangana": {
    "src": "/dishes/andhra-telangana.jpg",
    "credit": "Photo: Wikimedia Commons / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "north-india": {
    "src": "/dishes/north-india.jpg",
    "credit": "Photo: Shreya13jain / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "west-india": {
    "src": "/dishes/west-india.jpg",
    "credit": "Photo: Billjones94 / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "pongal": {
    "src": "/dishes/pongal.jpg",
    "credit": "Photo: Thilagavalli / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "curry-leaves": {
    "src": "/dishes/curry-leaves.jpg",
    "credit": "Photo: rovingI / CC BY 2.0 (Wikimedia Commons)"
  },
  "mustard-seeds": {
    "src": "/dishes/mustard-seeds.jpg",
    "credit": "Photo: Adityamadhav83 / CC BY-SA 3.0 (Wikimedia Commons)"
  },
  "rice": {
    "src": "/dishes/rice.jpg",
    "credit": "Photo: Basile Morin / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "toor-dal": {
    "src": "/dishes/toor-dal.jpg",
    "credit": "Photo: Monicasnk / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "tamarind": {
    "src": "/dishes/tamarind.jpg",
    "credit": "Photo: T.K. Naliaka / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "coconut": {
    "src": "/dishes/coconut.jpg",
    "credit": "Photo: Judgefloro / CC0 (Wikimedia Commons)"
  },
  "green-chilli": {
    "src": "/dishes/green-chilli.jpg",
    "credit": "Photo: Miansari66 / Public domain (Wikimedia Commons)"
  },
  "potato": {
    "src": "/dishes/potato.jpg",
    "credit": "Photo: gran / CC BY 3.0 (Wikimedia Commons)"
  },
  "onion": {
    "src": "/dishes/onion.jpg",
    "credit": "Photo: Colin / CC BY-SA 3.0 (Wikimedia Commons)"
  },
  "ghee": {
    "src": "/dishes/ghee.jpg",
    "credit": "Photo: JogiAsad / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "jaggery": {
    "src": "/dishes/jaggery.jpg",
    "credit": "Photo: Sanjoykanneth / CC BY-SA 4.0 (Wikimedia Commons)"
  },
  "coriander": {
    "src": "/dishes/coriander.jpg",
    "credit": "Photo: Home Cooking Secrets / CC BY-SA 3.0 (Wikimedia Commons)"
  }
};
